Repository ApolloAuto/apollo, pull requests merged in 2018-07, with the labels that each got.

#4748 Localization： Fix bug in local_map
  modules/localization/msf/local_map/lossless_map/lossless_map_matrix.cc
  modules/localization/msf/local_map/lossy_map/lossy_map_matrix_2d.cc
Labels: Module: Localization

#4930 Add documents for Chinese
  docs/howto/how_to_add_a_new_can_card_cn.md
  docs/howto/how_to_add_a_new_control_algorithm_cn.md
  docs/howto/how_to_add_a_new_evaluator_in_prediction_module_cn.md
  docs/howto/how_to_debug_dreamview_start_problem_cn.md
Labels: Module: Documents

#4926 commit dreamview_usage_table chinese version
  docs/specs/dreamview_usage_table_cn.md
Labels: Module: Documents

#4924 perception:Fix a code error of camera
  modules/perception/obstacle/camera/common/camera.h
Labels: Module: Perception

#4969 planning: extends the stitched trajectory from closest matching point
  modules/planning/common/trajectory/trajectory_stitcher.cc
  modules/planning/common/trajectory/trajectory_stitcher.h
Labels: Module: Planning

#4973 commit traffic_light chinese version
  docs/specs/traffic_light_cn.md
Labels: Module: Documents

#4970 Build and Release for VSCode
  README.md
  docs/FAQs/Hardware_FAQs.md
  docs/howto/how_to_build_and_release.md
  docs/howto/images/build_fail.png
Labels: Module: Documents
